Update devsecops.yml

diff --git a/.github/workflows/devsecops.yml b/.github/workflows/devsecops.yml
--- a/.github/workflows/devsecops.yml
+++ b/.github/workflows/devsecops.yml
@@ -28,12 +28,30 @@ jobs:
     - name: Run Safety (SCA)
       run: |
         pip install safety
-        safety check --full-report || true  # Allow failures but still generate report
+        mkdir -p reports
+        safety check --full-report > reports/safety-report.txt || true
+
+    - name: Upload Safety Report
+      uses: actions/upload-artifact@v4
+      with:
+         name: safety-report
+         path: reports/safety-report.txt
 
     - name: Run Bandit (SAST)
       run: |
-        pip install bandit
-        bandit -r app/ || true
+        mkdir -p reports
+        bandit -r app/ -f html -o reports/bandit-report.html || true
+
+    - name: Run Semgrep
+      uses: returntocorp/semgrep-action@v1
+      with:
+        config: "p/default"
+
+    - name: Upload Bandit Report
+      uses: actions/upload-artifact@v4
+      with:
+        name: bandit-report
+        path: reports/bandit-report.html
 
     - name: Login to Docker Hub
       uses: docker/login-action@v3
@@ -53,6 +71,30 @@ jobs:
         format: table
         exit-code: 1
         severity: CRITICAL,HIGH
+
+
+    - name: Run Dockle (Docker Best Practices)
+      uses: goodwithtech/dockle-action@v1
+      with:
+          image: mqtt-token-checker:latest
+
+    - name: Evaluate Vulnerability Risk Score
+      run: |
+          sudo apt-get install -y jq
+          docker save mqtt-token-checker:latest | trivy image --input - --format json -o report.json
+          HIGH=$(jq '[.Results[].Vulnerabilities[] | select(.Severity == "HIGH" or .Severity == "CRITICAL")] | length' report.json)
+          echo "Found $HIGH high or critical vulnerabilities"
+          if [ "$HIGH" -gt 5 ]; then
+            echo "Too many critical vulnerabilities. Failing build."
+            exit 1
+          fi
+
+    - name: Upload Trivy Report
+      uses: actions/upload-artifact@v4
+      with:
+          name: trivy-report
+          path: report.json
+          
     - name: Push the image to Docker Hub
       run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/mqtt-token-checker:latest
           
