Update devsecops.yml

diff --git a/.github/workflows/devsecops.yml b/.github/workflows/devsecops.yml
--- a/.github/workflows/devsecops.yml
+++ b/.github/workflows/devsecops.yml
@@ -34,8 +34,8 @@ jobs:
     - name: Upload Safety Report
       uses: actions/upload-artifact@v4
       with:
-         name: safety-report
-         path: reports/safety-report.txt
+        name: safety-report
+        path: reports/safety-report.txt
 
     - name: Run Bandit (SAST)
       run: |
@@ -43,7 +43,6 @@ jobs:
         mkdir -p reports
         bandit -r app/ -f html -o reports/bandit-report.html || true
 
-    
     - name: Upload Bandit Report
       uses: actions/upload-artifact@v4
       with:
@@ -62,25 +61,23 @@ jobs:
         docker tag mqtt-token-checker:latest ${{ secrets.DOCKERHUB_USERNAME }}/mqtt-token-checker:latest
 
     - name: Scan Docker Image with Trivy
-      uses: aquasecurity/trivy-action@v0.11.2
+      uses: aquasecurity/trivy-action@v0.13.1
       with:
         image-ref: mqtt-token-checker:latest
         format: json
         output: report.json
         severity: CRITICAL,HIGH
+        exit-code: 0 # Don't fail yet, we'll evaluate manually
 
-
-   
     - name: Evaluate Vulnerability Risk Score
       run: |
-       sudo apt-get install -y jq
-       HIGH=$(jq '[.Results[].Vulnerabilities[] | select(.Severity == "HIGH" or .Severity == "CRITICAL")] | length' report.json)
-       echo "Found $HIGH high or critical vulnerabilities"
-       if [ "$HIGH" -gt 5 ]; then
-         echo "Too many critical vulnerabilities. Failing build."
-         exit 1
-       fi
-
+        sudo apt-get install -y jq
+        HIGH=$(jq '[.Results[].Vulnerabilities[] | select(.Severity == "HIGH" or .Severity == "CRITICAL")] | length' report.json)
+        echo "Found $HIGH high or critical vulnerabilities"
+        if [ "$HIGH" -gt 5 ]; then
+          echo "Too many critical vulnerabilities. Failing build."
+          exit 1
+        fi
 
     - name: Upload Trivy Report
       uses: actions/upload-artifact@v4
